{ BtnMove.pas -- 2026-10-07, both Altium copies (Zulu_Altium_VS_Code and Zulu_Altium_VS_Code_HDI_Optimized).
  Generated by scratchpad btn/emit_pas.py from the plan that btn/btnplan.py checked against every copper layer
  (0 violations at 0.09 mm, 0.10/0.20 mm for the SDRAM classes on L3/L4, 0.24 mm hole to hole). See docs/btn_move.md.

  The user asked for BTN (PTS810, the user button) to move a little left, away from the RGB LEDs, and for X2's
  designator to be hidden. This script:
    1. moves BTN 0.5 mm west (pads 1/2 to x 18.725, pads 3/4 to x 20.875);
    2. moves three via stacks out of the new pad field:
         LED0_B    Top>L3 stack   (20.80, 10.60) -> (21.50, 10.55)
         N$BTN     Top>Bot stack  (22.00, 10.60) -> (20.875, 10.47), a filled microvia stack inside pad 3
         FT-RESETN Top>Bot stack  (18.45, 15.50) -> (18.15, 15.50)
    3. replaces BTN pad 1's VCC3V3 through via (18.50, 10.50) by a Top>L5 stack at (18.47, 10.45) inside pad 1
       (no legal through-via site exists there; the stack lands on the L5 VCC3V3 plane);
    4. re-draws the 14 tracks that end on those vias or pads and adds 3 new FT-RESETN tracks;
    5. hides X2's designator (C.NameOn := False).
  Afterwards: save, close, mark the three new laser vias as microvias with tools/stage13_mark_microvias.py
  (PCBObjectFactory vias default to the regular drill type), reopen, repour all polygons, DRC, save.
  Run BtnCanary first (reads only), then MoveBtn. MoveBtn changes nothing unless every object it edits is found. }

Var
    Brd  : IPCB_Board;
    Bad  : String;
    CBtn : IPCB_Component;
    CX2  : IPCB_Component;
    T01  : IPCB_Track;
    T02  : IPCB_Track;
    T03  : IPCB_Track;
    T04  : IPCB_Track;
    T05  : IPCB_Track;
    T06  : IPCB_Track;
    T07  : IPCB_Track;
    T08  : IPCB_Track;
    T09  : IPCB_Track;
    T10  : IPCB_Track;
    T11  : IPCB_Track;
    T12  : IPCB_Track;
    T13  : IPCB_Track;
    T14  : IPCB_Track;
    VL1  : TInterfaceList;
    VL2  : TInterfaceList;
    VL3  : TInterfaceList;
    VD1  : TInterfaceList;

Function PNear(A, B : Double) : Boolean;
Begin
    Result := Abs(A - B) < 0.002;
End;

Function DocOk : Boolean;
Var
    WS  : IWorkspace;
    Doc : IDocument;
    P   : String;
Begin
    Result := False;
    WS := GetWorkspace;
    If WS = Nil Then Exit;
    Doc := WS.DM_FocusedDocument;
    If Doc = Nil Then Exit;
    P := Doc.DM_FullPath;
    If (Pos('\Zulu_Altium_VS_Code\Imported zulu_a7.PrjPcb\zulu_a7.PcbDoc', P) = 0) And
       (Pos('\Zulu_Altium_VS_Code_HDI_Optimized\Imported zulu_a7.PrjPcb\zulu_a7_hdi_optimized.PcbDoc', P) = 0) Then
    Begin
        ShowMessage('Refusing to modify the focused document:' + #13#10 + P);
        Exit;
    End;
    Result := True;
End;

Function NetByName(AName : String) : IPCB_Net;
Var
    It : IPCB_BoardIterator;
    N  : IPCB_Net;
Begin
    Result := Nil;
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eNetObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);
    N := It.FirstPCBObject;
    While N <> Nil Do
    Begin
        If N.Name = AName Then Result := N;
        N := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
End;

Function FindTrk(ANet : String; L : TLayer; AX, AY, BX, BY : Double; Tag : String) : IPCB_Track;
Var
    It : IPCB_BoardIterator;
    T  : IPCB_Track;
    X1, Y1, X2, Y2 : Double;
    K  : Integer;
Begin
    Result := Nil;
    K := 0;
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eTrackObject));
    It.AddFilter_LayerSet(MkSet(L));
    It.AddFilter_Method(eProcessAll);
    T := It.FirstPCBObject;
    While T <> Nil Do
    Begin
        If (T.Net <> Nil) And (T.Layer = L) Then
            If T.Net.Name = ANet Then
            Begin
                X1 := CoordToMMs(T.X1); Y1 := CoordToMMs(T.Y1); X2 := CoordToMMs(T.X2); Y2 := CoordToMMs(T.Y2);
                If (PNear(X1, AX) And PNear(Y1, AY) And PNear(X2, BX) And PNear(Y2, BY)) Or
                   (PNear(X1, BX) And PNear(Y1, BY) And PNear(X2, AX) And PNear(Y2, AY)) Then
                Begin
                    Result := T;
                    K := K + 1;
                End;
            End;
        T := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
    If K <> 1 Then Bad := Bad + Tag + ' found ' + IntToStr(K) + 'x; ';
End;

Procedure GetVias(ANet : String; AX, AY : Double; Lst : TInterfaceList);
Var
    It : IPCB_BoardIterator;
    V  : IPCB_Via;
Begin
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eViaObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);
    V := It.FirstPCBObject;
    While V <> Nil Do
    Begin
        If V.Net <> Nil Then
            If (V.Net.Name = ANet) And PNear(CoordToMMs(V.X), AX) And PNear(CoordToMMs(V.Y), AY) Then Lst.Add(V);
        V := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
End;

Function PadAt(C : IPCB_Component; AName : String) : String;
Var
    It : IPCB_GroupIterator;
    P  : IPCB_Pad;
Begin
    Result := AName + ' not found';
    It := C.GroupIterator_Create;
    It.AddFilter_ObjectSet(MkSet(ePadObject));
    P := It.FirstPCBObject;
    While P <> Nil Do
    Begin
        If P.Name = AName Then Result := FloatToStr(CoordToMMs(P.X)) + ', ' + FloatToStr(CoordToMMs(P.Y));
        P := It.NextPCBObject;
    End;
    C.GroupIterator_Destroy(It);
End;

Function PadOk(C : IPCB_Component; AName : String; AX, AY : Double) : Boolean;
Var
    It : IPCB_GroupIterator;
    P  : IPCB_Pad;
Begin
    Result := False;
    It := C.GroupIterator_Create;
    It.AddFilter_ObjectSet(MkSet(ePadObject));
    P := It.FirstPCBObject;
    While P <> Nil Do
    Begin
        If (P.Name = AName) And PNear(CoordToMMs(P.X), AX) And PNear(CoordToMMs(P.Y), AY) Then Result := True;
        P := It.NextPCBObject;
    End;
    C.GroupIterator_Destroy(It);
End;

{ Re-draw a track: an end that the plan keeps keeps its exact old coordinate. }
Procedure EditTrk(T : IPCB_Track; AX, AY, BX, BY, NAX, NAY, NBX, NBY : Double);
Var
    Fwd : Boolean;
Begin
    Fwd := PNear(CoordToMMs(T.X1), AX) And PNear(CoordToMMs(T.Y1), AY);
    T.BeginModify;
    If Fwd Then
    Begin
        If Not (PNear(NAX, AX) And PNear(NAY, AY)) Then Begin T.X1 := MMsToCoord(NAX); T.Y1 := MMsToCoord(NAY); End;
        If Not (PNear(NBX, BX) And PNear(NBY, BY)) Then Begin T.X2 := MMsToCoord(NBX); T.Y2 := MMsToCoord(NBY); End;
    End
    Else
    Begin
        If Not (PNear(NAX, AX) And PNear(NAY, AY)) Then Begin T.X2 := MMsToCoord(NAX); T.Y2 := MMsToCoord(NAY); End;
        If Not (PNear(NBX, BX) And PNear(NBY, BY)) Then Begin T.X1 := MMsToCoord(NBX); T.Y1 := MMsToCoord(NBY); End;
    End;
    T.EndModify;
End;

Procedure MoveVias(Lst : TInterfaceList; AX, AY : Double);
Var
    I : Integer;
    V : IPCB_Via;
Begin
    For I := 0 To Lst.Count - 1 Do
    Begin
        V := Lst.Items[I];
        V.BeginModify;
        V.X := MMsToCoord(AX);
        V.Y := MMsToCoord(AY);
        V.EndModify;
    End;
End;

Procedure AddVia(N : IPCB_Net; AX, AY, Land, Hole : Double; LowL, HighL : TLayer);
Var
    V : IPCB_Via;
Begin
    V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    V.X := MMsToCoord(AX); V.Y := MMsToCoord(AY);
    V.Size := MMsToCoord(Land); V.HoleSize := MMsToCoord(Hole);
    V.LowLayer := LowL; V.HighLayer := HighL;
    V.Net := N; Brd.AddPCBObject(V); N.AddPCBObject(V);
End;

Procedure AddTrk(N : IPCB_Net; L : TLayer; W, X1, Y1, X2, Y2 : Double);
Var
    T : IPCB_Track;
Begin
    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    T.X1 := MMsToCoord(X1); T.Y1 := MMsToCoord(Y1);
    T.X2 := MMsToCoord(X2); T.Y2 := MMsToCoord(Y2);
    T.Layer := L;
    T.Width := MMsToCoord(W);
    T.Net := N;
    Brd.AddPCBObject(T);
    N.AddPCBObject(T);
End;

Procedure Collect;
Begin
    Bad := '';
    CBtn := Brd.GetPcbComponentByRefDes('BTN');
    CX2 := Brd.GetPcbComponentByRefDes('X2');
    If CBtn = Nil Then Bad := Bad + 'BTN missing; '
    Else
    Begin
        If Not PadOk(CBtn, '1', 19.2250, 10.8450) Then Bad := Bad + 'BTN pad 1 not at (19.225, 10.845); ';
        If Not PadOk(CBtn, '4', 21.3750, 14.9950) Then Bad := Bad + 'BTN pad 4 not at (21.375, 14.995); ';
    End;
    If CX2 = Nil Then Bad := Bad + 'X2 missing; ';
    If NetByName('VCC3V3') = Nil Then Bad := Bad + 'net VCC3V3 missing; ';
    If NetByName('FT-RESETN') = Nil Then Bad := Bad + 'net FT-RESETN missing; ';
    T01 := FindTrk('VCC3V3', eTopLayer, 18.5000, 10.5000, 19.2250, 10.8450, 'T01 VCC3V3 Top');
    T02 := FindTrk('VCC3V3', eTopLayer, 19.2200, 13.4400, 19.2250, 14.9950, 'T02 VCC3V3 Top');
    T03 := FindTrk('N$BTN', eTopLayer, 21.3750, 10.8450, 22.0000, 10.6000, 'T03 N$BTN Top');
    T04 := FindTrk('N$BTN', eTopLayer, 21.3000, 13.4000, 21.3750, 14.9950, 'T04 N$BTN Top');
    T05 := FindTrk('N$BTN', eTopLayer, 20.5000, 15.5000, 21.3750, 14.9950, 'T05 N$BTN Top');
    T06 := FindTrk('N$BTN', eBottomLayer, 21.3000, 11.3000, 22.0000, 10.6000, 'T06 N$BTN Bottom');
    T07 := FindTrk('LED0_B', eTopLayer, 20.8000, 10.6000, 20.8000, 11.3500, 'T07 LED0_B Top');
    T08 := FindTrk('LED0_B', eTopLayer, 20.8000, 11.3500, 21.0600, 11.6100, 'T08 LED0_B Top');
    T09 := FindTrk('LED0_B', eTopLayer, 21.0600, 11.6100, 22.6750, 11.6100, 'T09 LED0_B Top');
    T10 := FindTrk('LED0_B', eMidLayer1, 20.8000, 10.6000, 21.4500, 9.9500, 'T10 LED0_B L3');
    T11 := FindTrk('FT-RESETN', eTopLayer, 18.7000, 12.1500, 18.7000, 15.2500, 'T11 FT-RESETN Top');
    T12 := FindTrk('FT-RESETN', eTopLayer, 18.4500, 15.5000, 18.7000, 15.2500, 'T12 FT-RESETN Top');
    T13 := FindTrk('FT-RESETN', eTopLayer, 20.1500, 10.6000, 20.8000, 9.9500, 'T13 FT-RESETN Top');
    T14 := FindTrk('FT-RESETN', eBottomLayer, 18.4500, 15.5000, 19.1250, 16.1750, 'T14 FT-RESETN Bottom');
    VL1 := TInterfaceList.Create; GetVias('LED0_B', 20.8000, 10.6000, VL1);
    If VL1.Count <> 2 Then Bad := Bad + 'LED0_B vias at (20.8000, 10.6000): ' + IntToStr(VL1.Count) + ' (want 2); ';
    VL2 := TInterfaceList.Create; GetVias('N$BTN', 22.0000, 10.6000, VL2);
    If VL2.Count <> 5 Then Bad := Bad + 'N$BTN vias at (22.0000, 10.6000): ' + IntToStr(VL2.Count) + ' (want 5); ';
    VL3 := TInterfaceList.Create; GetVias('FT-RESETN', 18.4500, 15.5000, VL3);
    If VL3.Count <> 5 Then Bad := Bad + 'FT-RESETN vias at (18.4500, 15.5000): ' + IntToStr(VL3.Count) + ' (want 5); ';
    VD1 := TInterfaceList.Create; GetVias('VCC3V3', 18.5000, 10.5000, VD1);
    If VD1.Count <> 1 Then Bad := Bad + 'VCC3V3 via at (18.5000, 10.5000): ' + IntToStr(VD1.Count) + ' (want 1); ';
End;

Procedure FreeLists;
Begin
    VL1.Free;
    VL2.Free;
    VL3.Free;
    VD1.Free;
End;

Procedure BtnCanary;
Var
    S : String;
Begin
    If Not DocOk Then Exit;
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then Exit;
    Collect;
    S := 'BtnMove canary (changes nothing)' + #13#10;
    If CBtn <> Nil Then S := S + 'BTN origin ' + FloatToStr(CoordToMMs(CBtn.X)) + ', ' + FloatToStr(CoordToMMs(CBtn.Y)) +
        '  pad 1 at ' + PadAt(CBtn, '1') + #13#10;
    If CX2 <> Nil Then S := S + 'X2 designator shown: ' + BoolToStr(CX2.NameOn, True) + #13#10;
    If Bad = '' Then S := S + 'All 14 tracks and 13 vias found. MoveBtn may run.'
    Else S := S + 'NOT READY: ' + Bad;
    FreeLists;
    ShowMessage(S);
End;

Procedure MoveBtn;
Var
    NV, NR, N : IPCB_Net;
    S : String;
Begin
    If Not DocOk Then Exit;
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then Exit;
    Collect;
    If Bad <> '' Then
    Begin
        FreeLists;
        ShowMessage('BtnMove: nothing changed.' + #13#10 + Bad);
        Exit;
    End;
    NV := NetByName('VCC3V3');
    NR := NetByName('FT-RESETN');
    PCBServer.PreProcess;
    Try
        CBtn.BeginModify;
        CBtn.X := CBtn.X - MMsToCoord(0.5);
        CBtn.EndModify;
        If CX2.NameOn Then
        Begin
            CX2.BeginModify;
            CX2.NameOn := False;
            CX2.EndModify;
        End;
        Brd.RemovePCBObject(VD1.Items[0]);
        MoveVias(VL1, 21.5000, 10.5500);
        MoveVias(VL2, 20.8750, 10.4700);
        MoveVias(VL3, 18.1500, 15.5000);
        AddVia(NV, 18.4700, 10.4500, 0.3000, 0.1500, eTopLayer, eMidLayer3);
        AddVia(NV, 18.4700, 10.4500, 0.3000, 0.1500, eMidLayer3, eMidLayer1);
        AddVia(NV, 18.4700, 10.4500, 0.2700, 0.1500, eMidLayer1, eMidLayer2);
        AddVia(NV, 18.4700, 10.4500, 0.3000, 0.1500, eMidLayer2, eMidLayer4);
        EditTrk(T01, 18.5000, 10.5000, 19.2250, 10.8450, 18.4700, 10.4500, 18.7250, 10.8450);
        EditTrk(T02, 19.2200, 13.4400, 19.2250, 14.9950, 19.2200, 13.4400, 18.7250, 14.9950);
        EditTrk(T03, 21.3750, 10.8450, 22.0000, 10.6000, 20.8750, 10.4700, 20.8750, 10.8450);
        EditTrk(T04, 21.3000, 13.4000, 21.3750, 14.9950, 21.3000, 13.4000, 20.8750, 14.9950);
        EditTrk(T05, 20.5000, 15.5000, 21.3750, 14.9950, 20.5000, 15.5000, 20.8750, 14.9950);
        EditTrk(T06, 21.3000, 11.3000, 22.0000, 10.6000, 21.3000, 11.3000, 20.8750, 10.4700);
        EditTrk(T07, 20.8000, 10.6000, 20.8000, 11.3500, 21.5000, 10.5500, 21.5000, 11.2600);
        EditTrk(T08, 20.8000, 11.3500, 21.0600, 11.6100, 21.5000, 11.2600, 21.8500, 11.6100);
        EditTrk(T09, 21.0600, 11.6100, 22.6750, 11.6100, 21.8500, 11.6100, 22.6750, 11.6100);
        EditTrk(T10, 20.8000, 10.6000, 21.4500, 9.9500, 21.5000, 10.5500, 21.4500, 9.9500);
        EditTrk(T11, 18.7000, 12.1500, 18.7000, 15.2500, 18.7000, 12.1500, 18.7000, 13.9000);
        EditTrk(T12, 18.4500, 15.5000, 18.7000, 15.2500, 18.7000, 13.9000, 18.1500, 14.4500);
        EditTrk(T13, 20.1500, 10.6000, 20.8000, 9.9500, 20.1500, 10.6000, 20.1500, 10.3500);
        EditTrk(T14, 18.4500, 15.5000, 19.1250, 16.1750, 18.1500, 15.5000, 19.1250, 16.1750);
        AddTrk(NR, eTopLayer, 0.0762, 18.1500, 14.4500, 18.1500, 15.5000);
        AddTrk(NR, eTopLayer, 0.0762, 20.1500, 10.3500, 20.5500, 9.9500);
        AddTrk(NR, eTopLayer, 0.0762, 20.5500, 9.9500, 20.8000, 9.9500);
    Finally
        PCBServer.PostProcess;
    End;
    FreeLists;
    Brd.ViewManager_FullUpdate;
    S := 'BtnMove done.' + #13#10 + 'BTN pad 1 now at ' + PadAt(CBtn, '1') + ' (want 18.725, 10.845)' + #13#10 +
         'X2 designator shown: ' + BoolToStr(CX2.NameOn, True) + #13#10 +
         'Next: save, close, mark the 3 new laser vias, reopen, repour all, DRC.';
    ShowMessage(S);
End;
