# -*- coding: utf-8 -*-
"""Turn the verified placement from place_board.py into tools/ZuluPlacement.pas.

It refuses to write anything unless place_board.py's own checks pass first: every component
assigned, nothing off the board, and no two lands within 0.30 mm.

    python tools/emit_placement.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import place_board as pb

REPORT = os.path.join(HERE, 'placement_report.txt')

HEAD = """{..............................................................................}
{  ZuluPlacement.pas              DelphiScript for Altium Designer             }
{                                                                              }
{  Places all %(n)d components of zulu_a7.PcbDoc.                                  }
{                                                                              }
{  The table below is generated by tools/place_board.py, which derives it from }
{  docs/placement.html, the real land patterns in zulu_a7.PcbLib, the netlist,  }
{  the schematic sheet each part sits on, and the previous routed layout on the }
{  same outline. That script proves, BEFORE this one runs, that no two lands    }
{  come within 0.30 mm of each other and that nothing is within 0.30 mm of the  }
{  board edge.                                                                  }
{                                                                              }
{  EVERY TARGET IS A NAMED PAD, not Component.X/Y. Altium re-origins a          }
{  footprint on import, so the number it stores as Component.X is not one any   }
{  other tool can predict. What can be stated exactly is where a piece of       }
{  copper has to land. So each call names a reference pad and says where that   }
{  pad's centre goes; Place() sets the layer and rotation, reads Pad.X/Y back   }
{  through the API, and translates by the difference. Nothing depends on the    }
{  origin, and running the script twice changes nothing.                        }
{                                                                              }
{  Run:  File > Run Script... > PlaceAllComponents                              }
{        File > Run Script... > ReportPlacement    writes the result to a file  }
{  Then Ctrl+S. Only parameterless procedures appear in the picker.             }
{..............................................................................}

Var
    Brd     : IPCB_Board;
    Missing : String;
    NDone   : Integer;


{ helper - the pad bounding box of one component, in internal units }
Function PadBox(C : IPCB_Component; Var L, B, R, T : TCoord) : Boolean;
Var
    It : IPCB_GroupIterator;
    P  : IPCB_Primitive;
    RC : TCoordRect;
Begin
    Result := False;
    It := C.GroupIterator_Create;
    It.AddFilter_ObjectSet(MkSet(ePadObject));
    P := It.FirstPCBObject;
    While P <> Nil Do
    Begin
        RC := P.BoundingRectangle;
        If Not Result Then
        Begin
            L := RC.Left; B := RC.Bottom; R := RC.Right; T := RC.Top;
            Result := True;
        End
        Else
        Begin
            If RC.Left   < L Then L := RC.Left;
            If RC.Bottom < B Then B := RC.Bottom;
            If RC.Right  > R Then R := RC.Right;
            If RC.Top    > T Then T := RC.Top;
        End;
        P := It.NextPCBObject;
    End;
    C.GroupIterator_Destroy(It);
End;


{ helper - the centre of the pad called '1', so orientation can be checked and not assumed.
  X2 pin 1 has to land on (59.69, 24.13): that is the one number in the whole placement that
  the header's 2.54 mm grid, and therefore every mating carrier board, depends on. }
Function Pad1(C : IPCB_Component; Var PX, PY : TCoord) : Boolean;
Var
    It : IPCB_GroupIterator;
    P  : IPCB_Pad;
Begin
    Result := False;
    It := C.GroupIterator_Create;
    It.AddFilter_ObjectSet(MkSet(ePadObject));
    P := It.FirstPCBObject;
    While (P <> Nil) And (Not Result) Do
    Begin
        If P.Name = '1' Then
        Begin
            PX := P.X; PY := P.Y;
            Result := True;
        End;
        P := It.NextPCBObject;
    End;
    C.GroupIterator_Destroy(It);
End;


{ Lay 0 = top, 1 = bottom.  PN is the name of a reference pad and PX, PY are where that
  pad's CENTRE has to end up, in mm.

  This used to centre the component's pad BOUNDING BOX on a target instead, and that was wrong.
  Altium's Pad.BoundingRectangle is not the copper: for a through-hole pad it also covers the
  anti-pad the internal planes have to clear, so a 1.52 mm pin measures 2.53 mm across -- twice
  the 0.508 mm plane clearance wider. A pad that is ON the plane net gets a thermal relief and is
  not inflated at all. On a part with both, like JP3 (GND, TCK, TMS) or X1 (five signals and four
  grounded shield tabs), the box is LOPSIDED, so centring it puts the copper somewhere else. It
  also made the script non-idempotent: off the board there is no plane under the pad and the box
  is symmetric, so the first run was right and the second run shifted JP3 by 0.227 mm and X1 by
  0.175 mm.

  Pad.X and Pad.Y are the pad centre. Nothing inflates them. }
Procedure Place(D : String; Lay : Integer; Rot : Double; PN : String; PX, PY : Double);
Var
    C  : IPCB_Component;
    It : IPCB_GroupIterator;
    P  : IPCB_Pad;
    FX, FY : TCoord;
    Got    : Boolean;
Begin
    C := Brd.GetPcbComponentByRefDes(D);
    If C = Nil Then
    Begin
        Missing := Missing + D + ' ';
        Exit;
    End;

    C.BeginModify;
    If (Lay = 1) And (C.Layer <> eBottomLayer) Then C.Layer := eBottomLayer;
    If (Lay = 0) And (C.Layer <> eTopLayer)    Then C.Layer := eTopLayer;
    C.Rotation := Rot;
    C.EndModify;

    Got := False;
    If PN <> '' Then
    Begin
        It := C.GroupIterator_Create;
        It.AddFilter_ObjectSet(MkSet(ePadObject));
        P := It.FirstPCBObject;
        While (P <> Nil) And (Not Got) Do
        Begin
            If P.Name = PN Then
            Begin
                FX := P.X; FY := P.Y;
                Got := True;
            End;
            P := It.NextPCBObject;
        End;
        C.GroupIterator_Destroy(It);
    End;

    C.BeginModify;
    If Got Then
    Begin
        C.X := C.X + (MMsToCoord(PX) - FX);
        C.Y := C.Y + (MMsToCoord(PY) - FY);
    End
    Else
    Begin
        { the four Creative Commons marks carry no pads at all - position the origin }
        C.X := MMsToCoord(PX);
        C.Y := MMsToCoord(PY);
    End;
    C.EndModify;
    NDone := NDone + 1;
End;


Procedure PlaceAllComponents;
Begin
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then
    Begin
        ShowMessage('No PCB document is focused.' + #13#10 +
                    'Open zulu_a7.PcbDoc, click in the board window, and run again.');
        Exit;
    End;

    Missing := '';
    NDone   := 0;

    PCBServer.PreProcess;
    Try
"""

TAIL = """    Finally
        PCBServer.PostProcess;
    End;

    Brd.ViewManager_FullUpdate;

    ShowMessage('Zulu A7 - placement' + #13#10 + #13#10 +
                'Components placed: ' + IntToStr(NDone) + ' of %(n)d' + #13#10 +
                'Not found on the board: ' + Missing + #13#10 + #13#10 +
                'Nothing is saved yet - press Ctrl+S.' + #13#10 +
                'Then run ReportPlacement and check the file it writes.');
End;


{ VERIFICATION - re-measures every component and writes the result out.
  Every number is an INTEGER in internal units (1e-7 inch), so no decimal
  separator, and therefore no locale setting, can get into them.
      mm = value * 25.4 / 1e7                                            }
Procedure ReportPlacement;
Var
    It         : IPCB_BoardIterator;
    C          : IPCB_Component;
    S          : TStringList;
    L, B, R, T : TCoord;
    PX, PY     : TCoord;
    N          : Integer;
Begin
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then
    Begin
        ShowMessage('No PCB document is focused.');
        Exit;
    End;

    S := TStringList.Create;
    S.Add('# designator|layer|rotation|left|bottom|right|top|pad1x|pad1y   1e-7 inch');
    N := 0;

    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eComponentObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);
    C := It.FirstPCBObject;
    While C <> Nil Do
    Begin
        If Not PadBox(C, L, B, R, T) Then
        Begin
            L := C.X; B := C.Y; R := C.X; T := C.Y;
        End;
        If Not Pad1(C, PX, PY) Then
        Begin
            PX := 0; PY := 0;
        End;
        S.Add(C.Name.Text + '|' + Layer2String(C.Layer) + '|' +
              IntToStr(Round(C.Rotation)) + '|' + IntToStr(L) + '|' + IntToStr(B) + '|' +
              IntToStr(R) + '|' + IntToStr(T) + '|' + IntToStr(PX) + '|' + IntToStr(PY));
        N := N + 1;
        C := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);

    S.SaveToFile('%(report)s');
    S.Free;

    ShowMessage('Wrote ' + IntToStr(N) + ' components to' + #13#10 + '%(report)s');
End;

End.

{ End of ZuluPlacement.pas }
"""


def main():
    comp, ext, place, src, missing, overflow = pb.build(verbose=False)
    off, hits = pb.check(comp, pb.lib_geometry(), place)
    if off or hits or missing or overflow:
        print('refusing to emit: the placement is not clean '
              '(%d off-board, %d close pairs, %d unassigned, %d overflow)'
              % (len(off), len(hits), len(missing), len(overflow)))
        return 1

    import verify_copper as vc
    off = vc.lib_pad_offsets()

    body = []
    for anchors_first in (True, False):
        head = 'anchors, placed deliberately' if anchors_first else 'region fill'
        body.append('        { --- %s --- }' % head)
        keys = sorted(place, key=lambda k: (place[k][0] != 'top', k))
        for d in keys:
            is_anchor = not src[d].startswith('region')
            if is_anchor != anchors_first:
                continue
            layer, rot, cx, cy = place[d]
            pads = off.get(comp[d], {})
            # a reference pad Altium and this script can both name unambiguously
            ref = '1' if '1' in pads else (sorted(pads)[0] if pads else '')
            if ref:
                tx, ty = vc.transform(pads[ref][0], pads[ref][1], rot, layer == 'bottom')
                px, py = cx + tx, cy + ty
            else:
                px, py = cx, cy
            body.append("        Place(%-9s %d, %5.1f, %-5s %9.4f, %9.4f);   { %-6s %-22s %s }"
                        % ("'" + d + "',", 1 if layer == 'bottom' else 0, rot,
                           "'" + ref + "',", px, py, layer, comp[d], src[d]))
        body.append('')

    txt = (HEAD % {'n': len(place)}) + '\n'.join(body) + \
          (TAIL % {'n': len(place), 'report': REPORT})
    out = os.path.join(HERE, 'ZuluPlacement.pas')
    with open(out, 'w') as f:
        f.write(txt)
    print('wrote %s' % out)
    print('   %d Place calls, %d front / %d back'
          % (len(place),
             sum(1 for v in place.values() if v[0] == 'top'),
             sum(1 for v in place.values() if v[0] == 'bottom')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
