# -*- coding: utf-8 -*-
"""Turn tools/fanout_plan.json into DelphiScript that places it, and check the
plan against the board one last time before anything is written.

    python tools/fanout_emit.py            check the plan, print a summary
    python tools/fanout_emit.py --write    also regenerate the PlaceFanout /
                                           RemoveFanout block in tools/ZuluSetup.pas

WHAT IT CHECKS (independently of the planners' own checks)
  every via   : in a vacant, unblocked lattice cell or outside the land field;
                >= 0.09 mm from every U1 land edge with its 0.35 land; >= 0.44
                mm centre-to-centre from every other via; net names exist
  every track : straight; >= 0.09 mm (edge to edge) from every U1 land it does
                not serve; width legal for its net's Top rule; net names exist
  every ring-2 ball has a via; every netted core ball is connected

WHAT IT EMITS
  PlaceFanout  : one Via(...) / Trk(...) call per primitive, inside a single
                 PreProcess/PostProcess, nets looked up once by name
  RemoveFanout : deletes EVERY via on the board and EVERY track on the four
                 signal layers -- legitimate only while the fan-out is the only
                 routed copper, which is the case today (Vias6 empty, no
                 signal-layer track before the fan-out). It refuses to run if
                 the count it would delete exceeds the plan's count + 5.

Rows count from the top of the board (row A = largest y). Coordinates in mm.
"""
import io
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
INPUTS = os.path.join(HERE, 'fanout_inputs.json')
PLAN = os.path.join(HERE, 'fanout_plan.json')
SETUP = os.path.join(HERE, 'ZuluSetup.pas')
CLR = 0.09
VIA_LAND = 0.35
VIA_HOLE = 0.20
VIA_PITCH = 0.44
LAYER_ENUM = {'Top': 'eTopLayer', 'L3-SIG': 'eMidLayer1', 'L4-SIG': 'eMidLayer2', 'Bottom': 'eBottomLayer'}
BEGIN = '{ ==== FANOUT BLOCK, generated by tools/fanout_emit.py -- do not edit by hand ==== }'
END = '{ ==== END FANOUT BLOCK ==== }'


def top_min_width(net):
    if net == 'VCC1V0':
        return 0.15
    if net in ('VCC1V8', 'VCCADC', 'FT-VCORE', 'FT-VPHY', 'FT-VPLL'):
        return 0.15
    if net in ('VU', 'USB5V0', 'VBATT'):
        return 0.20
    return 0.0762


def seg_point_dist(x1, y1, x2, y2, px, py):
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return math.hypot(px - x1, py - y1)
    t = max(0.0, min(1.0, ((px - x1) * dx + (py - y1) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - (x1 + t * dx), py - (y1 + t * dy))


def check(inp, plan):
    balls = inp['balls']
    land_r = inp['grid']['land'] / 2
    blocked = {b['cell'] for b in inp['blocked']}
    vacant = {v['name']: v for v in inp['vacant']}
    nets = set(inp['nets'])
    problems = []
    vias = plan.get('vias', [])
    tracks = plan.get('tracks', [])
    for i, v in enumerate(vias):
        if v['net'] not in nets:
            problems.append('via %d net %r unknown' % (i, v['net']))
        if v.get('cell') and v['cell'] in blocked:
            problems.append('via %d in blocked cell %s' % (i, v['cell']))
        if v.get('cell') and v['cell'] not in vacant:
            problems.append('via %d cell %s is not vacant' % (i, v['cell']))
        for b in balls:
            d = math.hypot(v['x'] - b['x'], v['y'] - b['y']) - land_r - VIA_LAND / 2
            if d < CLR - 1e-6 and not (b['net'] == v['net'] and d > -1e-6):
                problems.append('via %d (%s) %.4f mm from land %s (%s)' % (i, v['net'], d, b['name'], b['net']))
        for j, w in enumerate(vias):
            if j <= i:
                continue
            d = math.hypot(v['x'] - w['x'], v['y'] - w['y'])
            if d < VIA_PITCH - 1e-6:
                problems.append('vias %d and %d %.4f mm apart' % (i, j, d))
    for i, t in enumerate(tracks):
        if t['net'] not in nets:
            problems.append('track %d net %r unknown' % (i, t['net']))
        if t['layer'] not in LAYER_ENUM:
            problems.append('track %d layer %r' % (i, t['layer']))
        if t['layer'] == 'Top' and t['width'] < top_min_width(t['net']) - 1e-6:
            problems.append('track %d (%s) width %.4f under the Top min %.4f' % (i, t['net'], t['width'], top_min_width(t['net'])))
        for b in balls:
            if b['net'] == t['net']:
                continue
            d = seg_point_dist(t['x1'], t['y1'], t['x2'], t['y2'], b['x'], b['y']) - land_r - t['width'] / 2
            if t['layer'] == 'Top' and d < CLR - 1e-6:
                problems.append('track %d (%s, Top) %.4f mm from land %s (%s)' % (i, t['net'], d, b['name'], b['net']))
    served = {v['net'] for v in vias}
    for b in balls:
        if b['ring'] == 2 and b['net']:
            near = [v for v in vias if v['net'] == b['net'] and math.hypot(v['x'] - b['x'], v['y'] - b['y']) < 1.6]
            if not near:
                problems.append('ring-2 ball %s (%s) has no via within 1.5 mm' % (b['name'], b['net']))
    return problems


def emit(plan):
    lines = [BEGIN, '',
             '{ Generated %s from tools/fanout_plan.json: %d vias, %d tracks. }' % (
                 __import__('datetime').date.today().isoformat(), len(plan['vias']), len(plan['tracks'])),
             '',
             'Function FanNet(AName : String) : IPCB_Net;',
             'Begin',
             '    Result := NetByName(AName);',
             'End;',
             '',
             'Procedure FanVia(N : IPCB_Net; X, Y : Double);',
             'Var',
             '    V : IPCB_Via;',
             'Begin',
             '    V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);',
             '    V.X         := MMsToCoord(X);',
             '    V.Y         := MMsToCoord(Y);',
             '    V.Size      := MMsToCoord(%.2f);' % VIA_LAND,
             '    V.HoleSize  := MMsToCoord(%.2f);' % VIA_HOLE,
             '    V.LowLayer  := eTopLayer;',
             '    V.HighLayer := eBottomLayer;',
             '    V.Net       := N;',
             '    Brd.AddPCBObject(V);',
             'End;',
             '',
             'Procedure FanTrk(N : IPCB_Net; L : TLayer; W, X1, Y1, X2, Y2 : Double);',
             'Var',
             '    T : IPCB_Track;',
             'Begin',
             '    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);',
             '    T.X1    := MMsToCoord(X1);',
             '    T.Y1    := MMsToCoord(Y1);',
             '    T.X2    := MMsToCoord(X2);',
             '    T.Y2    := MMsToCoord(Y2);',
             '    T.Layer := L;',
             '    T.Width := MMsToCoord(W);',
             '    T.Net   := N;',
             '    Brd.AddPCBObject(T);',
             'End;',
             '',
             'Procedure PlaceFanout;',
             'Var',
             '    N : IPCB_Net;',
             '    Missing : String;',
             'Begin',
             '    Brd := BoardOrNil;',
             '    If Brd = Nil Then Exit;',
             '    Missing := \'\';',
             '    PCBServer.PreProcess;',
             '    Try']
    # group primitives by net so each net is looked up once
    nets = sorted({v['net'] for v in plan['vias']} | {t['net'] for t in plan['tracks']})
    for net in nets:
        lines.append("        N := FanNet('%s');" % net.replace("'", "''"))
        lines.append("        If N = Nil Then Missing := Missing + ' %s' Else" % net.replace("'", "''"))
        lines.append('        Begin')
        for v in plan['vias']:
            if v['net'] == net:
                lines.append('            FanVia(N, %.4f, %.4f);' % (v['x'], v['y']))
        for t in plan['tracks']:
            if t['net'] == net:
                lines.append('            FanTrk(N, %s, %.4f, %.4f, %.4f, %.4f, %.4f);' % (
                    LAYER_ENUM[t['layer']], t['width'], t['x1'], t['y1'], t['x2'], t['y2']))
        lines.append('        End;')
    lines += ['    Finally',
              '        PCBServer.PostProcess;',
              '    End;',
              '    Brd.ViewManager_FullUpdate;',
              "    If Missing <> '' Then",
              "        ShowMessage('Zulu A7 - fan-out placed, but these nets were NOT found:' + Missing + #13#10 + 'Their primitives were skipped. Do not save until this is understood.')",
              '    Else',
              "        ShowMessage('Zulu A7 - fan-out placed: %d vias, %d tracks.' + #13#10 + #13#10 +" % (len(plan['vias']), len(plan['tracks'])),
              "                    'Now Tools > Design Rule Check > Run, then Ctrl+S if it is clean.');",
              'End;',
              '',
              '',
              'Procedure RemoveFanout;',
              'Var',
              '    It   : IPCB_BoardIterator;',
              '    P    : IPCB_Primitive;',
              '    Kill : TInterfaceList;',
              '    i    : Integer;',
              'Begin',
              '    Brd := BoardOrNil;',
              '    If Brd = Nil Then Exit;',
              '    Kill := TInterfaceList.Create;',
              '    It := Brd.BoardIterator_Create;',
              '    It.AddFilter_ObjectSet(MkSet(eViaObject, eTrackObject));',
              '    It.AddFilter_LayerSet(AllLayers);',
              '    It.AddFilter_Method(eProcessAll);',
              '    P := It.FirstPCBObject;',
              '    While P <> Nil Do',
              '    Begin',
              '        If (P.ObjectId = eViaObject) Or ((P.ObjectId = eTrackObject) And',
              '           ((P.Layer = eTopLayer) Or (P.Layer = eMidLayer1) Or (P.Layer = eMidLayer2) Or (P.Layer = eBottomLayer))) Then',
              '            Kill.Add(P);',
              '        P := It.NextPCBObject;',
              '    End;',
              '    Brd.BoardIterator_Destroy(It);',
              '    If Kill.Count > %d Then' % (len(plan['vias']) + len(plan['tracks']) + 5),
              '    Begin',
              "        ShowMessage('RemoveFanout would delete ' + IntToStr(Kill.Count) + ' objects, more than the fan-out placed - there is other routing on the board now. Nothing removed.');",
              '        Kill.Free;',
              '        Exit;',
              '    End;',
              '    PCBServer.PreProcess;',
              '    Try',
              '        For i := 0 To Kill.Count - 1 Do',
              '            Brd.RemovePCBObject(Kill.Items[i]);',
              '    Finally',
              '        PCBServer.PostProcess;',
              '    End;',
              '    Brd.ViewManager_FullUpdate;',
              "    ShowMessage('Zulu A7 - removed ' + IntToStr(Kill.Count) + ' fan-out object(s). Press Ctrl+S.');",
              '    Kill.Free;',
              'End;',
              '',
              END]
    return '\n'.join(lines) + '\n'


def main():
    inp = json.load(io.open(INPUTS, encoding='utf-8'))
    plan = json.load(io.open(PLAN, encoding='utf-8'))
    print('plan: %d vias, %d tracks' % (len(plan.get('vias', [])), len(plan.get('tracks', []))))
    problems = check(inp, plan)
    if problems:
        print('%d PROBLEM(S):' % len(problems))
        for p in problems[:40]:
            print('  ', p)
        if len(problems) > 40:
            print('   ... and %d more' % (len(problems) - 40))
        return 1
    print('geometry check: clean')
    if '--write' not in sys.argv:
        return 0
    block = emit(plan)
    s = io.open(SETUP, encoding='utf-8', errors='replace').read()
    tail = "End.\n\n{ End of ZuluSetup.pas }\n"
    assert s.endswith(tail)
    if BEGIN in s:
        a = s.index(BEGIN)
        b = s.index(END) + len(END) + 1
        s = s[:a] + block + s[b:]
    else:
        s = s[:-len(tail)] + '\n' + block + '\n' + tail
    io.open(SETUP, 'w', encoding='utf-8').write(s)
    print('wrote PlaceFanout / RemoveFanout into', os.path.normpath(SETUP))
    return 0


if __name__ == '__main__':
    sys.exit(main())
