{ X2PinLabels.pas -- 2026-10-07, generated by scratchpad x2labels/emit_pas.py from plan_labels.py.
  X2 pin number + short pin name on the TOP silkscreen (stroke font, 0.8 mm high, 0.15 mm stroke -- PCBWay's
  minimum), for the 33 pins with room: two lines (number nearest the pin, then the name) or one vertical line
  'N NAME' for pins 2, 21 and 30. Pins 1 and 4-9 stay unlabelled (U4, Q1 and R4 leave 0.9-1.5 mm; user's choice).
  Visible designators the labels displace are moved beside their parts (U2 on both boards, X3 on production);
  on the HDI board the 'ZULU A7' title moves to free space at 1.6 mm (no 2.0 mm spot is free).
  Run X2LabelsCanary (reads only), then PlaceX2LabelsProd or PlaceX2LabelsHdi on the matching board; save. }

Function DocIs(Frag : String) : Boolean;
Var
    WS  : IWorkspace;
    Doc : IDocument;
Begin
    Result := False;
    WS := GetWorkspace;
    If WS = Nil Then Exit;
    Doc := WS.DM_FocusedDocument;
    If Doc = Nil Then Exit;
    Result := Pos(Frag, Doc.DM_FullPath) > 0;
End;

Function TopTextCount(Brd : IPCB_Board; S : String) : Integer;
Var
    It : IPCB_BoardIterator;
    T  : IPCB_Text;
Begin
    Result := 0;
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eTextObject));
    It.AddFilter_LayerSet(MkSet(eTopOverlay));
    It.AddFilter_Method(eProcessAll);
    T := It.FirstPCBObject;
    While T <> Nil Do
    Begin
        If T.Text = S Then Result := Result + 1;
        T := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
End;

Procedure AddLabel(Brd : IPCB_Board; S : String; X, Y : Double; R : Integer);
Var
    T : IPCB_Text;
Begin
    T := PCBServer.PCBObjectFactory(eTextObject, eNoDimension, eCreate_Default);
    PCBServer.SendMessageToRobots(T.I_ObjectAddress, c_Broadcast, PCBM_BeginModify, c_NoEventData);
    T.XLocation := MMsToCoord(X);
    T.YLocation := MMsToCoord(Y);
    T.Layer := eTopOverlay;
    T.Text := S;
    T.Size := MMsToCoord(0.8);
    T.Width := MMsToCoord(0.15);
    T.Rotation := R;
    T.UseTTFonts := False;
    Brd.AddPCBObject(T);
    PCBServer.SendMessageToRobots(T.I_ObjectAddress, c_Broadcast, PCBM_EndModify, c_NoEventData);
    PCBServer.SendMessageToRobots(Brd.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);
End;

Procedure MoveDesignator(Brd : IPCB_Board; Ref : String; X, Y : Double);
Var
    C : IPCB_Component;
Begin
    C := Brd.GetPcbComponentByRefDes(Ref);
    If C = Nil Then Begin ShowMessage(Ref + ' not found'); Exit; End;
    C.ChangeNameAutoposition(eAutoPos_Manual);
    C.Name.MoveToXY(MMsToCoord(X), MMsToCoord(Y));
End;

Procedure MoveTitle(Brd : IPCB_Board; S : String; X, Y, H, W : Double);
Var
    It : IPCB_BoardIterator;
    T  : IPCB_Text;
Begin
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eTextObject));
    It.AddFilter_LayerSet(MkSet(eTopOverlay));
    It.AddFilter_Method(eProcessAll);
    T := It.FirstPCBObject;
    While T <> Nil Do
    Begin
        If T.Text = S Then
        Begin
            T.BeginModify;
            T.Size := MMsToCoord(H);
            T.Width := MMsToCoord(W);
            T.XLocation := MMsToCoord(X);
            T.YLocation := MMsToCoord(Y);
            T.EndModify;
        End;
        T := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
End;

Procedure X2LabelsCanary;
Var
    Brd : IPCB_Board;
    C   : IPCB_Component;
    S   : String;
Begin
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then Begin ShowMessage('No PCB focused.'); Exit; End;
    S := 'Top-overlay texts: 1V0=' + IntToStr(TopTextCount(Brd, '1V0')) + ', ZULU A7=' + IntToStr(TopTextCount(Brd, 'ZULU A7'));
    C := Brd.GetPcbComponentByRefDes('U2');
    If C <> Nil Then S := S + #13#10 + 'U2 name at ' + FloatToStr(CoordToMMs(C.Name.XLocation)) + ', ' + FloatToStr(CoordToMMs(C.Name.YLocation));
    C := Brd.GetPcbComponentByRefDes('X3');
    If C <> Nil Then S := S + #13#10 + 'X3 name at ' + FloatToStr(CoordToMMs(C.Name.XLocation)) + ', ' + FloatToStr(CoordToMMs(C.Name.YLocation));
    S := S + #13#10 + 'eAutoPos_Manual = ' + IntToStr(eAutoPos_Manual);
    ShowMessage(S);
End;


Procedure PlaceX2LabelsProd;
Var
    Brd : IPCB_Board;
Begin
    If Not DocIs('\Zulu_Altium_VS_Code\Imported zulu_a7.PrjPcb\zulu_a7.PcbDoc') Then Begin ShowMessage('Refusing: focus \Zulu_Altium_VS_Code\Imported zulu_a7.PrjPcb\zulu_a7.PcbDoc'); Exit; End;
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then Exit;
    If TopTextCount(Brd, '1V0') > 0 Then Begin ShowMessage('X2 labels already present; nothing changed.'); Exit; End;
    PCBServer.PreProcess;
    AddLabel(Brd, '2 CLK', 57.55, 19.2554, 90);
    AddLabel(Brd, '3', 54.3432, 22.189, 0);
    AddLabel(Brd, 'C0', 53.9432, 20.939, 0);
    AddLabel(Brd, '10', 26.1302, 22.189, 0);
    AddLabel(Brd, 'C7', 26.1302, 20.939, 0);
    AddLabel(Brd, '11', 23.5902, 22.189, 0);
    AddLabel(Brd, 'C8', 23.5902, 20.939, 0);
    AddLabel(Brd, '12', 21.0502, 22.189, 0);
    AddLabel(Brd, 'C9', 21.0502, 20.939, 0);
    AddLabel(Brd, '13', 18.5102, 22.189, 0);
    AddLabel(Brd, 'C10', 18.1102, 20.939, 0);
    AddLabel(Brd, '14', 15.9702, 22.189, 0);
    AddLabel(Brd, 'C11', 15.5702, 20.939, 0);
    AddLabel(Brd, '15', 13.4302, 22.189, 0);
    AddLabel(Brd, 'C12', 13.0302, 20.939, 0);
    AddLabel(Brd, '16', 10.8902, 22.189, 0);
    AddLabel(Brd, 'C13', 10.4902, 20.939, 0);
    AddLabel(Brd, '17', 8.3502, 22.189, 0);
    AddLabel(Brd, 'GND', 7.9502, 20.939, 0);
    AddLabel(Brd, '18', 5.8102, 22.189, 0);
    AddLabel(Brd, '3V3', 5.4102, 20.939, 0);
    AddLabel(Brd, '19', 3.2702, 22.189, 0);
    AddLabel(Brd, '1V8', 2.8702, 20.939, 0);
    AddLabel(Brd, '20', 0.7302, 22.189, 0);
    AddLabel(Brd, '1V0', 0.3302, 20.939, 0);
    AddLabel(Brd, '21 GND', 60.09, 2.411, 90);
    AddLabel(Brd, '22', 56.4832, 2.411, 0);
    AddLabel(Brd, 'VU', 56.4832, 3.661, 0);
    AddLabel(Brd, '23', 53.9432, 2.411, 0);
    AddLabel(Brd, 'RST', 53.5432, 3.661, 0);
    AddLabel(Brd, '24', 51.4032, 2.411, 0);
    AddLabel(Brd, 'C14', 51.0032, 3.661, 0);
    AddLabel(Brd, '25', 48.8632, 2.411, 0);
    AddLabel(Brd, 'C15', 48.4632, 3.661, 0);
    AddLabel(Brd, '26', 46.3232, 2.411, 0);
    AddLabel(Brd, 'C16', 45.9232, 3.661, 0);
    AddLabel(Brd, '27', 43.7832, 2.411, 0);
    AddLabel(Brd, 'C17', 43.3832, 3.661, 0);
    AddLabel(Brd, '28', 41.2432, 2.411, 0);
    AddLabel(Brd, 'C18', 40.8432, 3.661, 0);
    AddLabel(Brd, '29', 38.7032, 2.411, 0);
    AddLabel(Brd, 'C19', 38.3032, 3.661, 0);
    AddLabel(Brd, '30 C20', 27.07, 2.411, 90);
    AddLabel(Brd, '31', 23.5902, 2.411, 0);
    AddLabel(Brd, 'C21', 23.1902, 3.661, 0);
    AddLabel(Brd, '32', 21.0502, 2.411, 0);
    AddLabel(Brd, 'C22', 20.6502, 3.661, 0);
    AddLabel(Brd, '33', 18.5102, 2.411, 0);
    AddLabel(Brd, 'C23', 18.1102, 3.661, 0);
    AddLabel(Brd, '34', 15.9702, 2.411, 0);
    AddLabel(Brd, 'C24', 15.5702, 3.661, 0);
    AddLabel(Brd, '35', 13.4302, 2.411, 0);
    AddLabel(Brd, 'C25', 13.0302, 3.661, 0);
    AddLabel(Brd, '36', 10.8902, 2.411, 0);
    AddLabel(Brd, 'C26', 10.4902, 3.661, 0);
    AddLabel(Brd, '37', 8.3502, 2.411, 0);
    AddLabel(Brd, 'C27', 7.9502, 3.661, 0);
    AddLabel(Brd, '38', 5.8102, 2.411, 0);
    AddLabel(Brd, 'C28', 5.4102, 3.661, 0);
    AddLabel(Brd, '39', 3.2702, 2.411, 0);
    AddLabel(Brd, 'AI0', 2.8702, 3.661, 0);
    AddLabel(Brd, '40', 0.7302, 2.411, 0);
    AddLabel(Brd, 'AI1', 0.3302, 3.661, 0);
    MoveDesignator(Brd, 'U2', 23.509, 19.639);
    MoveDesignator(Brd, 'X3', 1.0833, 19.2504);
    PCBServer.PostProcess;
    Brd.ViewManager_FullUpdate;
    ShowMessage('63 X2 label texts added; 2 text(s) moved. Run DRC, then save.');
End;

Procedure PlaceX2LabelsHdi;
Var
    Brd : IPCB_Board;
Begin
    If Not DocIs('\Zulu_Altium_VS_Code_HDI_Optimized\Imported zulu_a7.PrjPcb\zulu_a7_hdi_optimized.PcbDoc') Then Begin ShowMessage('Refusing: focus \Zulu_Altium_VS_Code_HDI_Optimized\Imported zulu_a7.PrjPcb\zulu_a7_hdi_optimized.PcbDoc'); Exit; End;
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then Exit;
    If TopTextCount(Brd, '1V0') > 0 Then Begin ShowMessage('X2 labels already present; nothing changed.'); Exit; End;
    PCBServer.PreProcess;
    AddLabel(Brd, '2 CLK', 57.55, 19.2554, 90);
    AddLabel(Brd, '3', 54.3432, 22.189, 0);
    AddLabel(Brd, 'C0', 53.9432, 20.939, 0);
    AddLabel(Brd, '10', 26.1302, 22.189, 0);
    AddLabel(Brd, 'C7', 26.1302, 20.939, 0);
    AddLabel(Brd, '11', 23.5902, 22.189, 0);
    AddLabel(Brd, 'C8', 23.5902, 20.939, 0);
    AddLabel(Brd, '12', 21.0502, 22.189, 0);
    AddLabel(Brd, 'C9', 21.0502, 20.939, 0);
    AddLabel(Brd, '13', 18.5102, 22.189, 0);
    AddLabel(Brd, 'C10', 18.1102, 20.939, 0);
    AddLabel(Brd, '14', 15.9702, 22.189, 0);
    AddLabel(Brd, 'C11', 15.5702, 20.939, 0);
    AddLabel(Brd, '15', 13.4302, 22.189, 0);
    AddLabel(Brd, 'C12', 13.0302, 20.939, 0);
    AddLabel(Brd, '16', 10.8902, 22.189, 0);
    AddLabel(Brd, 'C13', 10.4902, 20.939, 0);
    AddLabel(Brd, '17', 8.3502, 22.189, 0);
    AddLabel(Brd, 'GND', 7.9502, 20.939, 0);
    AddLabel(Brd, '18', 5.8102, 22.189, 0);
    AddLabel(Brd, '3V3', 5.4102, 20.939, 0);
    AddLabel(Brd, '19', 3.2702, 22.189, 0);
    AddLabel(Brd, '1V8', 2.8702, 20.939, 0);
    AddLabel(Brd, '20', 0.7302, 22.189, 0);
    AddLabel(Brd, '1V0', 0.3302, 20.939, 0);
    AddLabel(Brd, '21 GND', 60.09, 2.411, 90);
    AddLabel(Brd, '22', 56.4832, 2.411, 0);
    AddLabel(Brd, 'VU', 56.4832, 3.661, 0);
    AddLabel(Brd, '23', 53.9432, 2.411, 0);
    AddLabel(Brd, 'RST', 53.5432, 3.661, 0);
    AddLabel(Brd, '24', 51.4032, 2.411, 0);
    AddLabel(Brd, 'C14', 51.0032, 3.661, 0);
    AddLabel(Brd, '25', 48.8632, 2.411, 0);
    AddLabel(Brd, 'C15', 48.4632, 3.661, 0);
    AddLabel(Brd, '26', 46.3232, 2.411, 0);
    AddLabel(Brd, 'C16', 45.9232, 3.661, 0);
    AddLabel(Brd, '27', 43.7832, 2.411, 0);
    AddLabel(Brd, 'C17', 43.3832, 3.661, 0);
    AddLabel(Brd, '28', 41.2432, 2.411, 0);
    AddLabel(Brd, 'C18', 40.8432, 3.661, 0);
    AddLabel(Brd, '29', 38.7032, 2.411, 0);
    AddLabel(Brd, 'C19', 38.3032, 3.661, 0);
    AddLabel(Brd, '30 C20', 27.07, 2.411, 90);
    AddLabel(Brd, '31', 23.5902, 2.411, 0);
    AddLabel(Brd, 'C21', 23.1902, 3.661, 0);
    AddLabel(Brd, '32', 21.0502, 2.411, 0);
    AddLabel(Brd, 'C22', 20.6502, 3.661, 0);
    AddLabel(Brd, '33', 18.5102, 2.411, 0);
    AddLabel(Brd, 'C23', 18.1102, 3.661, 0);
    AddLabel(Brd, '34', 15.9702, 2.411, 0);
    AddLabel(Brd, 'C24', 15.5702, 3.661, 0);
    AddLabel(Brd, '35', 13.4302, 2.411, 0);
    AddLabel(Brd, 'C25', 13.0302, 3.661, 0);
    AddLabel(Brd, '36', 10.8902, 2.411, 0);
    AddLabel(Brd, 'C26', 10.4902, 3.661, 0);
    AddLabel(Brd, '37', 8.3502, 2.411, 0);
    AddLabel(Brd, 'C27', 7.9502, 3.661, 0);
    AddLabel(Brd, '38', 5.8102, 2.411, 0);
    AddLabel(Brd, 'C28', 5.4102, 3.661, 0);
    AddLabel(Brd, '39', 3.2702, 2.411, 0);
    AddLabel(Brd, 'AI0', 2.8702, 3.661, 0);
    AddLabel(Brd, '40', 0.7302, 2.411, 0);
    AddLabel(Brd, 'AI1', 0.3302, 3.661, 0);
    MoveDesignator(Brd, 'U2', 23.509, 19.639);
    MoveTitle(Brd, 'ZULU A7', 37.5, 5.25, 1.6, 0.2);
    PCBServer.PostProcess;
    Brd.ViewManager_FullUpdate;
    ShowMessage('63 X2 label texts added; 2 text(s) moved. Run DRC, then save.');
End;
