{..............................................................................}
{  ZuluPlacement.pas              DelphiScript for Altium Designer             }
{                                                                              }
{  Places all 175 components of zulu_a7.PcbDoc.                                  }
{                                                                              }
{  The table below is generated by tools/place_board.py, which derives it from }
{  docs/placement.html, the real land patterns in zulu_a7.PcbLib, the netlist,  }
{  the schematic sheet each part sits on, and the previous routed layout on the }
{  same outline. That script proves, BEFORE this one runs, that no two lands    }
{  come within 0.30 mm of each other and that nothing is within 0.30 mm of the  }
{  board edge.                                                                  }
{                                                                              }
{  EVERY TARGET IS A NAMED PAD, not Component.X/Y. Altium re-origins a          }
{  footprint on import, so the number it stores as Component.X is not one any   }
{  other tool can predict. What can be stated exactly is where a piece of       }
{  copper has to land. So each call names a reference pad and says where that   }
{  pad's centre goes; Place() sets the layer and rotation, reads Pad.X/Y back   }
{  through the API, and translates by the difference. Nothing depends on the    }
{  origin, and running the script twice changes nothing.                        }
{                                                                              }
{  Run:  File > Run Script... > PlaceAllComponents                              }
{        File > Run Script... > ReportPlacement    writes the result to a file  }
{  Then Ctrl+S. Only parameterless procedures appear in the picker.             }
{..............................................................................}

Var
    Brd     : IPCB_Board;
    Missing : String;
    NDone   : Integer;


{ helper - the pad bounding box of one component, in internal units }
Function PadBox(C : IPCB_Component; Var L, B, R, T : TCoord) : Boolean;
Var
    It : IPCB_GroupIterator;
    P  : IPCB_Primitive;
    RC : TCoordRect;
Begin
    Result := False;
    It := C.GroupIterator_Create;
    It.AddFilter_ObjectSet(MkSet(ePadObject));
    P := It.FirstPCBObject;
    While P <> Nil Do
    Begin
        RC := P.BoundingRectangle;
        If Not Result Then
        Begin
            L := RC.Left; B := RC.Bottom; R := RC.Right; T := RC.Top;
            Result := True;
        End
        Else
        Begin
            If RC.Left   < L Then L := RC.Left;
            If RC.Bottom < B Then B := RC.Bottom;
            If RC.Right  > R Then R := RC.Right;
            If RC.Top    > T Then T := RC.Top;
        End;
        P := It.NextPCBObject;
    End;
    C.GroupIterator_Destroy(It);
End;


{ helper - the centre of the pad called '1', so orientation can be checked and not assumed.
  X2 pin 1 has to land on (59.69, 24.13): that is the one number in the whole placement that
  the header's 2.54 mm grid, and therefore every mating carrier board, depends on. }
Function Pad1(C : IPCB_Component; Var PX, PY : TCoord) : Boolean;
Var
    It : IPCB_GroupIterator;
    P  : IPCB_Pad;
Begin
    Result := False;
    It := C.GroupIterator_Create;
    It.AddFilter_ObjectSet(MkSet(ePadObject));
    P := It.FirstPCBObject;
    While (P <> Nil) And (Not Result) Do
    Begin
        If P.Name = '1' Then
        Begin
            PX := P.X; PY := P.Y;
            Result := True;
        End;
        P := It.NextPCBObject;
    End;
    C.GroupIterator_Destroy(It);
End;


{ Lay 0 = top, 1 = bottom.  PN is the name of a reference pad and PX, PY are where that
  pad's CENTRE has to end up, in mm.

  This used to centre the component's pad BOUNDING BOX on a target instead, and that was wrong.
  Altium's Pad.BoundingRectangle is not the copper: for a through-hole pad it also covers the
  anti-pad the internal planes have to clear, so a 1.52 mm pin measures 2.53 mm across -- twice
  the 0.508 mm plane clearance wider. A pad that is ON the plane net gets a thermal relief and is
  not inflated at all. On a part with both, like JP3 (GND, TCK, TMS) or X1 (five signals and four
  grounded shield tabs), the box is LOPSIDED, so centring it puts the copper somewhere else. It
  also made the script non-idempotent: off the board there is no plane under the pad and the box
  is symmetric, so the first run was right and the second run shifted JP3 by 0.227 mm and X1 by
  0.175 mm.

  Pad.X and Pad.Y are the pad centre. Nothing inflates them. }
Procedure Place(D : String; Lay : Integer; Rot : Double; PN : String; PX, PY : Double);
Var
    C  : IPCB_Component;
    It : IPCB_GroupIterator;
    P  : IPCB_Pad;
    FX, FY : TCoord;
    Got    : Boolean;
Begin
    C := Brd.GetPcbComponentByRefDes(D);
    If C = Nil Then
    Begin
        Missing := Missing + D + ' ';
        Exit;
    End;

    C.BeginModify;
    If (Lay = 1) And (C.Layer <> eBottomLayer) Then C.Layer := eBottomLayer;
    If (Lay = 0) And (C.Layer <> eTopLayer)    Then C.Layer := eTopLayer;
    C.Rotation := Rot;
    C.EndModify;

    Got := False;
    If PN <> '' Then
    Begin
        It := C.GroupIterator_Create;
        It.AddFilter_ObjectSet(MkSet(ePadObject));
        P := It.FirstPCBObject;
        While (P <> Nil) And (Not Got) Do
        Begin
            If P.Name = PN Then
            Begin
                FX := P.X; FY := P.Y;
                Got := True;
            End;
            P := It.NextPCBObject;
        End;
        C.GroupIterator_Destroy(It);
    End;

    C.BeginModify;
    If Got Then
    Begin
        C.X := C.X + (MMsToCoord(PX) - FX);
        C.Y := C.Y + (MMsToCoord(PY) - FY);
    End
    Else
    Begin
        { the four Creative Commons marks carry no pads at all - position the origin }
        C.X := MMsToCoord(PX);
        C.Y := MMsToCoord(PY);
    End;
    C.EndModify;
    NDone := NDone + 1;
End;


Procedure PlaceAllComponents;
Begin
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then
    Begin
        ShowMessage('No PCB document is focused.' + #13#10 +
                    'Open zulu_a7.PcbDoc, click in the board window, and run again.');
        Exit;
    End;

    Missing := '';
    NDone   := 0;

    PCBServer.PreProcess;
    Try
        { --- anchors, placed deliberately --- }
        Place('BTN',    0,  90.0, '1',    19.2251,   10.8451);   { top    PTS810                 old board }
        Place('J1',     0,  90.0, '1',    65.1300,    6.3500);   { top    2X06                   plan }
        Place('JP3',    0,   0.0, '1',    61.7600,   21.6800);   { top    1X03-NOSILK            geometry }
        Place('JP4',    0,   0.0, '1',    61.7600,    3.7200);   { top    1X03-NOSILK            geometry }
        Place('LD0',    0,   0.0, '1',    25.2749,   11.6099);   { top    EVERLIGHT-19-337       old board }
        Place('LD1',    0,   0.0, 'A',    23.7999,   12.5850);   { top    LED0603                old board }
        Place('LD2',    0,   0.0, 'A',    23.7999,   13.7850);   { top    LED0603                old board }
        Place('LD3',    0,   0.0, 'A',    23.7999,   16.1850);   { top    LED0603                geometry }
        Place('LD4',    0,   0.0, 'A',    23.7999,   17.3850);   { top    LED0603                geometry }
        Place('LD5',    0,   0.0, 'A',    23.7999,   14.9850);   { top    LED0603                old board }
        Place('Q1',     0,   0.0, '1',    40.4500,   20.8499);   { top    32X25                  geometry }
        Place('R4',     0,  90.0, '1',    60.1499,   15.3779);   { top    742C163                geometry }
        Place('U$3',    0,   0.0, '',      3.0000,   21.2000);   { top    CC_BY                  geometry }
        Place('U$4',    0,   0.0, '',      7.0000,   21.2000);   { top    CC_SA                  geometry }
        Place('U1',     0,   0.0, 'A1',   41.9000,   16.4000);   { top    XC7A35T-CPG236         plan }
        Place('U2',     0,   0.0, '1',    27.2500,   17.3501);   { top    FT2232HL-LQFP64        geometry }
        Place('U4',     0,   0.0, '1',    43.8500,   21.3050);   { top    SOIC-8_208MIL          geometry }
        Place('X1',     0,   0.0, '1',    34.3200,   21.2585);   { top    MOLEX-105017-0001      plan+old agree }
        Place('X2',     0,   0.0, '1',    59.6900,   24.1300);   { top    ZULU-DIP37             plan+old agree }
        Place('X3',     0,  90.0, '1',    14.1500,   15.6749);   { top    DM3D-SF                plan }
        Place('X4',     0,   0.0, '1',    31.4000,    3.0501);   { top    JST-B2B-PH-SM4-TB      plan }
        Place('R1',     1,   0.0, '1',    57.8000,    4.5499);   { bottom 742C043                geometry }
        Place('R34',    1,   0.0, '1',    10.6200,   20.1899);   { bottom 742C083                old board }
        Place('U$2',    1,   0.0, '',     45.0000,   12.7000);   { bottom CC_CC                  geometry }
        Place('U$5',    1,   0.0, '',     53.0000,   12.7000);   { bottom CC_COPYRIGHT           geometry }
        Place('U10',    1,   0.0, '1',    22.2851,   18.6950);   { bottom SPI-8_SOIC_150         geometry }
        Place('U3',     1,  90.0, '1',    38.7500,    6.1701);   { bottom TSOPII-54              plan }

        { --- region fill --- }
        Place('C140',   0,  90.0, '1',    53.0001,    5.8500);   { top    C0805                  region TE }
        Place('C141',   0,  90.0, '1',    54.8002,    5.8500);   { top    C0805                  region TE }
        Place('C142',   0,  90.0, '1',    56.6003,    5.8500);   { top    C0805                  region TE }
        Place('C143',   0,  90.0, '1',    53.0001,    9.1497);   { top    C0805                  region TE }
        Place('C144',   0,  90.0, '1',    54.8002,    9.1497);   { top    C0805                  region TE }
        Place('C145',   0,  90.0, '1',    56.6003,    9.1497);   { top    C0805                  region TE }
        Place('C146',   0,  90.0, '1',    53.0001,   12.4495);   { top    C0805                  region TE }
        Place('C85',    0,  90.0, '1',    54.8002,   12.4495);   { top    C0805                  region TE }
        Place('C86',    0,  90.0, '1',    56.6003,   12.4495);   { top    C0805                  region TE }
        Place('C93',    0,  90.0, '1',    53.0001,   15.7492);   { top    C0805                  region TE }
        Place('C97',    0,  90.0, '1',    54.8002,   15.7492);   { top    C0805                  region TE }
        Place('C98',    0,  90.0, '1',    56.6003,   15.7492);   { top    C0805                  region TE }
        Place('C100',   1,   0.0, '1',    40.3500,   21.1000);   { bottom C0603                  region BULKN }
        Place('C101',   1,   0.0, '1',    43.4499,   21.1000);   { bottom C0603                  region BULKN }
        Place('C102',   1,   0.0, '1',    46.5497,   21.1000);   { bottom C0603                  region BULKN }
        Place('C103',   1,   0.0, '1',    49.6496,   21.1000);   { bottom C0603                  region BULKN }
        Place('C104',   1,   0.0, '1',    52.7494,   21.1000);   { bottom C0603                  region BULKN }
        Place('C105',   1,   0.0, '1',    55.8492,   21.1000);   { bottom C0603                  region BULKN }
        Place('C106',   1,   0.0, '1',    40.3500,   22.4000);   { bottom C0603                  region BULKN }
        Place('C107',   1,   0.0, '1',    46.5900,    7.6500);   { bottom C0201                  region DEC }
        Place('C108',   1,   0.0, '1',    42.1500,   11.0500);   { bottom C0201                  region DEC }
        Place('C109',   1,   0.0, '1',    44.3700,    7.6500);   { bottom C0201                  region DEC }
        Place('C11',    1,   0.0, '1',     4.6499,   21.3900);   { bottom C0402                  region NW }
        Place('C110',   1,   0.0, '1',    48.8100,    7.6500);   { bottom C0201                  region DEC }
        Place('C111',   1,   0.0, '1',    51.0300,   11.0500);   { bottom C0201                  region DEC }
        Place('C112',   1,   0.0, '1',    42.1500,   14.4500);   { bottom C0201                  region DEC }
        Place('C113',   1,   0.0, '1',    42.1500,    7.6500);   { bottom C0201                  region DEC }
        Place('C114',   1,   0.0, '1',    51.0300,   14.4500);   { bottom C0201                  region DEC }
        Place('C115',   1,   0.0, '1',    51.0300,    7.6500);   { bottom C0201                  region DEC }
        Place('C116',   1,   0.0, '1',    46.5900,   17.8500);   { bottom C0201                  region DEC }
        Place('C117',   1,   0.0, '1',    44.3700,   17.8500);   { bottom C0201                  region DEC }
        Place('C118',   1,   0.0, '1',    48.8100,   17.8500);   { bottom C0201                  region DEC }
        Place('C119',   1,   0.0, '1',    53.2501,   11.0500);   { bottom C0201                  region DEC }
        Place('C12',    1,   0.0, '1',     6.9498,   21.3900);   { bottom C0402                  region NW }
        Place('C120',   1,   0.0, '1',    42.1500,   17.8500);   { bottom C0201                  region DEC }
        Place('C121',   1,   0.0, '1',    53.2501,   14.4500);   { bottom C0201                  region DEC }
        Place('C122',   1,   0.0, '1',    53.2501,    7.6500);   { bottom C0201                  region DEC }
        Place('C123',   1,   0.0, '1',    53.5503,    3.0500);   { bottom C0402                  region CFG }
        Place('C124',   1,   0.0, '1',    47.9500,    4.2499);   { bottom C0402                  region CFG }
        Place('C13',    1,   0.0, '1',     1.7500,   21.4400);   { bottom C0603                  region NW }
        Place('C133',   1,   0.0, '1',    22.1500,    3.9499);   { bottom C0201                  region UNDER }
        Place('C134',   1,   0.0, '1',    23.3499,    3.9499);   { bottom C0201                  region UNDER }
        Place('C135',   1,   0.0, '1',    24.5498,    3.9499);   { bottom C0201                  region UNDER }
        Place('C136',   1,   0.0, '1',    25.7497,    3.9499);   { bottom C0201                  region UNDER }
        Place('C137',   1,   0.0, '1',    26.9497,    3.9499);   { bottom C0201                  region UNDER }
        Place('C138',   1,   0.0, '1',    28.1496,    3.9499);   { bottom C0201                  region UNDER }
        Place('C139',   1,   0.0, '1',    23.3503,    3.0500);   { bottom C0402                  region UNDER }
        Place('C147',   1,   0.0, '1',     1.8500,   11.2500);   { bottom C0805                  region PWR }
        Place('C148',   1,   0.0, '1',     5.1497,   11.2500);   { bottom C0805                  region PWR }
        Place('C149',   1,   0.0, '1',     8.4495,   11.2500);   { bottom C0805                  region PWR }
        Place('C150',   1,   0.0, '1',     5.0498,   12.8000);   { bottom C0603                  region PWR }
        Place('C151',   1,   0.0, '1',     8.1496,   12.8000);   { bottom C0603                  region PWR }
        Place('C152',   1,   0.0, '1',    29.3495,    3.9499);   { bottom C0201                  region UNDER }
        Place('C153',   1,   0.0, '1',    30.5494,    3.9499);   { bottom C0201                  region UNDER }
        Place('C154',   1,   0.0, '1',    31.7494,    3.9499);   { bottom C0201                  region UNDER }
        Place('C3',     1,   0.0, '1',    25.6503,    3.0500);   { bottom C0402                  region UNDER }
        Place('C36',    1,   0.0, '1',    40.3500,    3.0500);   { bottom C0402                  region XADC }
        Place('C37',    1,   0.0, '1',    42.6500,    3.0500);   { bottom C0402                  region XADC }
        Place('C38',    1,   0.0, '1',    32.9493,    3.9499);   { bottom C0201                  region UNDER }
        Place('C4',     1,   0.0, '1',    27.9502,    3.0500);   { bottom C0402                  region UNDER }
        Place('C40',    1,   0.0, '1',    34.1492,    3.9499);   { bottom C0201                  region UNDER }
        Place('C41',    1,   0.0, '1',    35.3491,    3.9499);   { bottom C0201                  region UNDER }
        Place('C5',     1,   0.0, '1',    30.2502,    3.0500);   { bottom C0402                  region UNDER }
        Place('C6',     1,   0.0, '1',    32.5502,    3.0500);   { bottom C0402                  region UNDER }
        Place('C7',     1,   0.0, '1',    34.8502,    3.0500);   { bottom C0402                  region UNDER }
        Place('C78',    1,   0.0, '1',    11.7492,   11.2500);   { bottom C0805                  region PWR }
        Place('C8',     1,   0.0, '1',    37.1502,    3.0500);   { bottom C0402                  region UNDER }
        Place('C80',    1,   0.0, '1',     1.8500,   13.0501);   { bottom C0805                  region PWR }
        Place('C82',    1,   0.0, '1',    11.2495,   12.8000);   { bottom C0603                  region PWR }
        Place('C84',    1,   0.0, '1',     1.7500,   14.6002);   { bottom C0603                  region PWR }
        Place('C87',    1,   0.0, '1',    43.4499,   22.4000);   { bottom C0603                  region BULKN }
        Place('C88',    1,   0.0, '1',    46.5497,   22.4000);   { bottom C0603                  region BULKN }
        Place('C89',    1,   0.0, '1',    46.5900,   11.0500);   { bottom C0201                  region DEC }
        Place('C9',     1,   0.0, '1',    17.7500,    4.2499);   { bottom C0402                  region UNDER }
        Place('C90',    1,   0.0, '1',    44.3700,   11.0500);   { bottom C0201                  region DEC }
        Place('C91',    1,   0.0, '1',    48.8100,   11.0500);   { bottom C0201                  region DEC }
        Place('C92',    1,   0.0, '1',    46.5900,   14.4500);   { bottom C0201                  region DEC }
        Place('C94',    1,   0.0, '1',    49.6496,   22.4000);   { bottom C0603                  region BULKN }
        Place('C95',    1,   0.0, '1',    48.8100,   14.4500);   { bottom C0201                  region DEC }
        Place('C96',    1,   0.0, '1',    44.3700,   14.4500);   { bottom C0201                  region DEC }
        Place('C99',    1,   0.0, '1',    52.7494,   22.4000);   { bottom C0603                  region BULKN }
        Place('L1',     1,   0.0, '1',     4.3250,    9.0499);   { bottom IND2520                region PWR }
        Place('L2',     1,   0.0, '1',     8.0250,    9.0499);   { bottom IND2520                region PWR }
        Place('L3',     1,   0.0, '1',    11.7251,    9.0499);   { bottom IND2520                region PWR }
        Place('L4',     1,   0.0, '1',    17.8500,    3.0500);   { bottom IND0603                region UNDER }
        Place('L5',     1,   0.0, '1',    20.6501,    3.0500);   { bottom IND0603                region UNDER }
        Place('L6',     1,   0.0, '1',    48.0500,    3.0500);   { bottom IND0603                region CFG }
        Place('L7',     1,   0.0, '1',    50.8501,    3.0500);   { bottom IND0603                region CFG }
        Place('Q2',     1,   0.0, 'D',     2.3500,    8.3499);   { bottom SOT23-3                region PWR }
        Place('R10',    1,   0.0, '1',    44.7500,    2.7500);   { bottom R0201                  region XADC }
        Place('R101',   1,   0.0, '1',    17.5500,   18.7500);   { bottom R0201                  region SDL }
        Place('R102',   1,   0.0, '1',     4.6499,   14.5501);   { bottom R0402                  region PWR }
        Place('R103',   1,   0.0, '1',     6.9498,   14.5501);   { bottom R0402                  region PWR }
        Place('R104',   1,   0.0, '1',     9.2498,   14.5501);   { bottom R0402                  region PWR }
        Place('R105',   1,   0.0, '1',    11.5498,   14.5501);   { bottom R0402                  region PWR }
        Place('R106',   1,   0.0, '1',     1.5500,   15.8501);   { bottom R0402                  region PWR }
        Place('R107',   1,   0.0, '1',     3.8500,   15.8501);   { bottom R0402                  region PWR }
        Place('R108',   1,   0.0, '1',     6.1500,   15.8501);   { bottom R0402                  region PWR }
        Place('R11',    1,   0.0, '1',    45.9499,    2.7500);   { bottom R0201                  region XADC }
        Place('R12',    1,   0.0, '1',    40.1500,    3.9499);   { bottom R0201                  region XADC }
        Place('R13',    1,   0.0, '1',    41.3499,    3.9499);   { bottom R0201                  region XADC }
        Place('R14',    1,   0.0, '1',    42.5498,    3.9499);   { bottom R0201                  region XADC }
        Place('R15',    1,   0.0, '1',    43.7498,    3.9499);   { bottom R0201                  region XADC }
        Place('R16',    1,   0.0, '1',    44.9497,    3.9499);   { bottom R0201                  region XADC }
        Place('R17',    1,   0.0, '1',    46.1496,    3.9499);   { bottom R0201                  region XADC }
        Place('R18',    1,   0.0, '1',    20.0500,    4.2499);   { bottom R0402                  region UNDER }
        Place('R19',    1,   0.0, '1',    18.7499,   18.7500);   { bottom R0201                  region SDL }
        Place('R2',     1,   0.0, '1',    55.4492,   22.0500);   { bottom R0201                  region BULKN }
        Place('R20',    1,   0.0, '1',    52.3500,    3.9499);   { bottom R0201                  region CFG }
        Place('R21',    1,   0.0, '1',    50.2500,    4.2499);   { bottom R0402                  region CFG }
        Place('R22',    1,   0.0, '1',    53.5499,    3.9499);   { bottom R0201                  region CFG }
        Place('R23',    1,   0.0, '1',    54.7498,    3.9499);   { bottom R0201                  region CFG }
        Place('R24',    1,   0.0, '1',    58.7500,    5.6500);   { bottom R0201                  region EAST }
        Place('R25',    1,   0.0, '1',    60.8000,    5.6500);   { bottom R0201                  region EAST }
        Place('R26',    1,   0.0, '1',    62.8501,    5.6500);   { bottom R0201                  region EAST }
        Place('R27',    1,   0.0, '1',    58.7500,    8.4900);   { bottom R0201                  region EAST }
        Place('R28',    1,   0.0, '1',    60.8000,    8.4900);   { bottom R0201                  region EAST }
        Place('R29',    1,   0.0, '1',    62.8501,    8.4900);   { bottom R0201                  region EAST }
        Place('R30',    1,   0.0, '1',    58.7500,   11.3300);   { bottom R0201                  region EAST }
        Place('R31',    1,   0.0, '1',    60.8000,   11.3300);   { bottom R0201                  region EAST }
        Place('R32',    1,   0.0, '1',    62.8501,   11.3300);   { bottom R0201                  region EAST }
        Place('R33',    1,   0.0, '1',    58.7500,   14.1700);   { bottom R0201                  region EAST }
        Place('R35',    1,   0.0, '1',     9.2498,   21.3900);   { bottom R0402                  region NW }
        Place('R5',     1,   0.0, '1',    60.8000,   14.1700);   { bottom R0201                  region EAST }
        Place('R6',     1,   0.0, '1',    56.6491,   22.0500);   { bottom R0201                  region BULKN }
        Place('R7',     1,   0.0, '1',    57.8490,   22.0500);   { bottom R0201                  region BULKN }
        Place('R77',    1,   0.0, '1',     8.4500,   15.8501);   { bottom R0402                  region PWR }
        Place('R78',    1,   0.0, '1',    10.7500,   15.8501);   { bottom R0402                  region PWR }
        Place('R80',    1,   0.0, '1',    28.9000,   19.0500);   { bottom R0402                  region SDR }
        Place('R81',    1,   0.0, '1',    31.2000,   19.0500);   { bottom R0402                  region SDR }
        Place('R82',    1,   0.0, '1',    33.5000,   19.0500);   { bottom R0402                  region SDR }
        Place('R83',    1,   0.0, '1',    35.8000,   19.0500);   { bottom R0402                  region SDR }
        Place('R84',    1,   0.0, '1',    28.9000,   20.2499);   { bottom R0402                  region SDR }
        Place('R85',    1,   0.0, '1',    31.2000,   20.2499);   { bottom R0402                  region SDR }
        Place('R86',    1,   0.0, '1',    33.5000,   20.2499);   { bottom R0402                  region SDR }
        Place('R90',    1,   0.0, '1',    62.8501,   14.1700);   { bottom R0201                  region EAST }
        Place('R91',    1,   0.0, '1',    58.7500,   17.0100);   { bottom R0201                  region EAST }
        Place('R92',    1,   0.0, '1',    60.8000,   17.0100);   { bottom R0201                  region EAST }
        Place('R93',    1,   0.0, '1',    62.8501,   17.0100);   { bottom R0201                  region EAST }
        Place('R94',    1,   0.0, '1',    58.7500,   19.8500);   { bottom R0201                  region EAST }
        Place('R96',    1,   0.0, '1',    19.9498,   18.7500);   { bottom R0201                  region SDL }
        Place('R97',    1,   0.0, '1',    17.5500,   19.3500);   { bottom R0201                  region SDL }
        Place('R98',    1,   0.0, '1',    18.7499,   19.3500);   { bottom R0201                  region SDL }
        Place('R99',    1,   0.0, '1',    60.8000,   19.8500);   { bottom R0201                  region EAST }
        Place('U5',     1,   0.0, '1',     1.5000,    7.0499);   { bottom SOT23-5                region PWR }
        Place('U6',     1,   0.0, '1',     4.2998,    7.0499);   { bottom SOT23-5                region PWR }
        Place('U7',     1,   0.0, '1',     7.0997,    7.0499);   { bottom SOT23-5                region PWR }
        Place('U8',     1,   0.0, '1',     9.8996,    4.9500);   { bottom VQFN16-3X3-RGT         region PWR }
    Finally
        PCBServer.PostProcess;
    End;

    Brd.ViewManager_FullUpdate;

    ShowMessage('Zulu A7 - placement' + #13#10 + #13#10 +
                'Components placed: ' + IntToStr(NDone) + ' of 175' + #13#10 +
                'Not found on the board: ' + Missing + #13#10 + #13#10 +
                'Nothing is saved yet - press Ctrl+S.' + #13#10 +
                'Then run ReportPlacement and check the file it writes.');
End;


{ VERIFICATION - re-measures every component and writes the result out.
  Every number is an INTEGER in internal units (1e-7 inch), so no decimal
  separator, and therefore no locale setting, can get into them.
      mm = value * 25.4 / 1e7                                            }
Procedure ReportPlacement;
Var
    It         : IPCB_BoardIterator;
    C          : IPCB_Component;
    S          : TStringList;
    L, B, R, T : TCoord;
    PX, PY     : TCoord;
    N          : Integer;
Begin
    Brd := PCBServer.GetCurrentPCBBoard;
    If Brd = Nil Then
    Begin
        ShowMessage('No PCB document is focused.');
        Exit;
    End;

    S := TStringList.Create;
    S.Add('# designator|layer|rotation|left|bottom|right|top|pad1x|pad1y   1e-7 inch');
    N := 0;

    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eComponentObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);
    C := It.FirstPCBObject;
    While C <> Nil Do
    Begin
        If Not PadBox(C, L, B, R, T) Then
        Begin
            L := C.X; B := C.Y; R := C.X; T := C.Y;
        End;
        If Not Pad1(C, PX, PY) Then
        Begin
            PX := 0; PY := 0;
        End;
        S.Add(C.Name.Text + '|' + Layer2String(C.Layer) + '|' +
              IntToStr(Round(C.Rotation)) + '|' + IntToStr(L) + '|' + IntToStr(B) + '|' +
              IntToStr(R) + '|' + IntToStr(T) + '|' + IntToStr(PX) + '|' + IntToStr(PY));
        N := N + 1;
        C := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);

    S.SaveToFile('C:\Users\tambe\Documents\Electronics\Zulu_A7\Zulu_Altrium\tools\placement_report.txt');
    S.Free;

    ShowMessage('Wrote ' + IntToStr(N) + ' components to' + #13#10 + 'C:\Users\tambe\Documents\Electronics\Zulu_A7\Zulu_Altrium\tools\placement_report.txt');
End;

End.

{ End of ZuluPlacement.pas }
