{ ==== STAGE13HDIPROBE BLOCK, generated by tools/route_emit.py -- do not edit by hand ==== }

Procedure PlaceStage13HdiProbe;
Var
    N    : IPCB_Net;
    V    : IPCB_Via;
    T    : IPCB_Track;
    It   : IPCB_BoardIterator;
    Kill : TInterfaceList;
    i    : Integer;
    x, y, x2, y2, tw : Double;
    nm   : String;
    Missing : String;
Begin
    Brd := BoardOrNil;
    If Brd = Nil Then Exit;
    Missing := '';
    Kill := TInterfaceList.Create;
    PCBServer.PreProcess;
    Try
        For i := 0 To Kill.Count - 1 Do
            Brd.RemovePCBObject(Kill.Items[i]);
        N := FanNet('CHAN0');
        If N = Nil Then Missing := Missing + ' CHAN0' Else
        Begin
            { laser via Top/L2-GND of plan span Top/L2-GND/L3-SIG }
            V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
            V.X := MMsToCoord(2.5000); V.Y := MMsToCoord(2.0000);
            V.Size := MMsToCoord(0.3000); V.HoleSize := MMsToCoord(0.1500);
            V.LowLayer := eTopLayer; V.HighLayer := eMidLayer3;
            V.Net := N; Brd.AddPCBObject(V); N.AddPCBObject(V);
            { laser via L2-GND/L3-SIG of plan span Top/L2-GND/L3-SIG }
            V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
            V.X := MMsToCoord(2.5000); V.Y := MMsToCoord(2.0000);
            V.Size := MMsToCoord(0.3000); V.HoleSize := MMsToCoord(0.1500);
            V.LowLayer := eMidLayer3; V.HighLayer := eMidLayer1;
            V.Net := N; Brd.AddPCBObject(V); N.AddPCBObject(V);
            FanTrk(N, eTopLayer, 0.0762, 2.0000, 2.0000, 2.5000, 2.0000);
            FanTrk(N, eMidLayer1, 0.0762, 2.5000, 2.0000, 3.0000, 2.0000);
        End;
        N := FanNet('GND');
        If N = Nil Then Missing := Missing + ' GND' Else
        Begin
            { laser via Top/L2-GND of plan span Top/L2-GND }
            V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
            V.X := MMsToCoord(2.5000); V.Y := MMsToCoord(2.7500);
            V.Size := MMsToCoord(0.3000); V.HoleSize := MMsToCoord(0.1500);
            V.LowLayer := eTopLayer; V.HighLayer := eMidLayer3;
            V.Net := N; Brd.AddPCBObject(V); N.AddPCBObject(V);
        End;
    Finally
        PCBServer.PostProcess;
    End;
    Kill.Free;
    Brd.ViewManager_FullUpdate;
    If Missing <> '' Then
        ShowMessage('Zulu A7 - Stage13HdiProbe placed, but these nets were NOT found:' + Missing + #13#10 + 'Their primitives were skipped. Do not save until this is understood.')
    Else
        ShowMessage('Zulu A7 - Stage13HdiProbe placed: removed 0, added 3 via objects (2 plan vias) and 2 tracks.' + #13#10 + 'Now Tools > Design Rule Check > Run, then Ctrl+S if it is clean.');
End;


Procedure RemoveStage13HdiProbe;
Var
    N    : IPCB_Net;
    V    : IPCB_Via;
    T    : IPCB_Track;
    It   : IPCB_BoardIterator;
    Kill : TInterfaceList;
    i    : Integer;
    x, y, x2, y2, tw : Double;
    nm   : String;
    Missing : String;
Begin
    Brd := BoardOrNil;
    If Brd = Nil Then Exit;
    Missing := '';
    Kill := TInterfaceList.Create;
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eViaObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);
    V := It.FirstPCBObject;
    While V <> Nil Do
    Begin
        nm := ''; If V.Net <> Nil Then nm := V.Net.Name;
        x := CoordToMMs(V.X); y := CoordToMMs(V.Y);
        If (((nm = 'CHAN0') And (Abs(x - 2.5000) < 0.001) And (Abs(y - 2.0000) < 0.001)) And (V.LowLayer = eTopLayer) And (V.HighLayer = eMidLayer3)) Then Kill.Add(V);
        If (((nm = 'CHAN0') And (Abs(x - 2.5000) < 0.001) And (Abs(y - 2.0000) < 0.001)) And (V.LowLayer = eMidLayer3) And (V.HighLayer = eMidLayer1)) Then Kill.Add(V);
        If (((nm = 'GND') And (Abs(x - 2.5000) < 0.001) And (Abs(y - 2.7500) < 0.001)) And (V.LowLayer = eTopLayer) And (V.HighLayer = eMidLayer3)) Then Kill.Add(V);
        V := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
    It := Brd.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eTrackObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);
    T := It.FirstPCBObject;
    While T <> Nil Do
    Begin
        nm := ''; If T.Net <> Nil Then nm := T.Net.Name;
        x := CoordToMMs(T.X1); y := CoordToMMs(T.Y1); x2 := CoordToMMs(T.X2); y2 := CoordToMMs(T.Y2);
        tw := CoordToMMs(T.Width);
        If ((nm = 'CHAN0') And (T.Layer = eTopLayer) And (Abs(tw - 0.0762) < 0.0005) And (((Abs(x - 2.0000) < 0.001) And (Abs(y - 2.0000) < 0.001) And (Abs(x2 - 2.5000) < 0.001) And (Abs(y2 - 2.0000) < 0.001)) Or ((Abs(x - 2.5000) < 0.001) And (Abs(y - 2.0000) < 0.001) And (Abs(x2 - 2.0000) < 0.001) And (Abs(y2 - 2.0000) < 0.001)))) Then Kill.Add(T);
        If ((nm = 'CHAN0') And (T.Layer = eMidLayer1) And (Abs(tw - 0.0762) < 0.0005) And (((Abs(x - 2.5000) < 0.001) And (Abs(y - 2.0000) < 0.001) And (Abs(x2 - 3.0000) < 0.001) And (Abs(y2 - 2.0000) < 0.001)) Or ((Abs(x - 3.0000) < 0.001) And (Abs(y - 2.0000) < 0.001) And (Abs(x2 - 2.5000) < 0.001) And (Abs(y2 - 2.0000) < 0.001)))) Then Kill.Add(T);
        T := It.NextPCBObject;
    End;
    Brd.BoardIterator_Destroy(It);
    PCBServer.PreProcess;
    Try
        For i := 0 To Kill.Count - 1 Do
            Brd.RemovePCBObject(Kill.Items[i]);
    Finally
        PCBServer.PostProcess;
    End;
    Brd.ViewManager_FullUpdate;
    ShowMessage('Zulu A7 - removed ' + IntToStr(Kill.Count) + ' Stage13HdiProbe object(s) (expected 5). Press Ctrl+S.');
    Kill.Free;
End;

{ ==== END STAGE13HDIPROBE BLOCK ==== }
